# Generated by Django 3.2.7 on 2021-11-11 02:48

from django.db import migrations, models

# Esta es una clase auto generada por el framework de desarrollo al usar el comando python manage.py makemigrations y python manage.py migrate
# Se genera el modelo Usuario, que además le da permisos de superusuario al agregar los atributos is_staff e is_admin

class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
